### PR TITLE
Add input box to create project

### PR DESCRIPTION
**Pull request by ruairif**
create_project
[Fix problem with project creation](https://github.com/scrapinghub/portia/issues/648#issuecomment-270632607)

### CODE REVIEW

**Comment by michalmo** [comment]
Maybe this should be in the reverse order. Choose a project or create a new one.

**Comment by ruairif** [comment]
when it's done this way both options are easily available without needing to scroll

**Comment by eng1neer** [comment]
When creating a project with the name "example.com" it gets added to the project list but an alert flashes `Project with id 'undefined' not found`. I guess that dot symbol is not allowed in project name?

**Comment by sagelliv** [comment]
@eng1neer Did it work with a non-dotted name then?

**Comment by eng1neer** [comment]
@sagelliv  It did, but the project with dotted name was still created in somewhat corrupted state. It refused to load on click with the same error.

**Comment by ruairif** [comment]
@eng1neer I've updated the PR to disallow project names containing a `.` thanks for pointing this out

**Pull request merged**
